### ISSUE TITLE
Addon stopped working in Anki 25.09.2 (3890e12c) (ao)

### ISSUE THREAD

**Issue by homocomputeris** [Ajatt-Tools/Japanese#27]
```
Add-on Startup Failed
The following add-ons failed to load: ⁨
[AJT Japanese Furigana Pitch Accent Native pronunciations](https://ankiweb.net/shared/info/1344485230)⁩
They may need to be updated to support this version of Anki. Click the Check for Updates button to see if any updates are available.
You can use the Copy Debug Info button to get information that you can paste in a report to the add-on author.
For add-ons that don't have an update available, you can disable or delete the add-on to prevent this message from appearing.
```

```
Anki 25.09.2 (3890e12c) (ao)
Python 3.14.2 Qt 6.10.1 PyQt 6.10.2
Platform: Linux-6.18.5-2-cachyos-x86_64-with-glibc2.42

When loading AJT Japanese  Furigana Pitch Accent Native pronunciations:
Traceback (most recent call last):
  File "/usr/lib/python3.14/site-packages/aqt/addons.py", line 250, in loadAddons
    __import__(addon.dir_name)
    ~~~~~~~~~~^^^^^^^^^^^^^^^^
  File "/home/user/.local/share/Anki2/addons21/1344485230/__init__.py", line 36, in <module>
    start_addon()
    ~~~~~~~~~~~^^
  File "/home/user/.local/share/Anki2/addons21/1344485230/__init__.py", line 10, in start_addon
    from . import (
    ...<7 lines>...
    )
  File "/home/user/.local/share/Anki2/addons21/1344485230/bulk_add.py", line 16, in <module>
    from .tasks import DoTasks
  File "/home/user/.local/share/Anki2/addons21/1344485230/tasks.py", line 18, in <module>
    from .audio import aud_src_mgr, format_audio_tags
  File "/home/user/.local/share/Anki2/addons21/1344485230/audio.py", line 19, in <module>
    from .audio_manager.audio_manager import AudioSourceManagerFactory
  File "/home/user/.local/share/Anki2/addons21/1344485230/audio_manager/audio_manager.py", line 8, in <module>
    from ..config_view import JapaneseConfig
  File "/home/user/.local/share/Anki2/addons21/1344485230/config_view.py", line 18, in <module>
    from .mecab_controller.kana_conv import to_katakana
  File "/home/user/.local/share/Anki2/addons21/1344485230/mecab_controller/__init__.py", line 6, in <module>
    from .mecab_controller import BasicMecabController, MecabController
  File "/home/user/.local/share/Anki2/addons21/1344485230/mecab_controller/mecab_controller.py", line 11, in <module>
    from .basic_types import (
    ...<5 lines>...
    )
  File "/home/user/.local/share/Anki2/addons21/1344485230/mecab_controller/basic_types.py", line 116, in <module>
    assert tuple(field.name for field in dataclasses.fields(MecabParsedToken)) == tuple(COMPONENTS.__annotations__)
                                                                                        ^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'MecabAnalysis' object has no attribute '__annotations__'. Did you mean: '__annotate_func__'?
```
```
pacman -Qs mecab
local/mecab-git r157.61b90ba-1
    Yet another part-of-speech and morphological analyzer.
local/mecab-ipadic 2.7.0_20070801-10
    IPA dictionary for mecab
local/mecab-ipadic-neologd-git r20200914-1
    Neologism dictionary for MeCab
```

**Comment by tatsumoto-ren** [comment]
We had this issue reported a few days ago. It occurs after upgrading python to 3.14, and should be fixed already. Try updating the add-on. 

https://t.me/c/1431051090/31518/80364

**Comment by Bobo1239** [comment]
If anybody else encounters this issue: On my machine I had to reinstall the plugin to fix this issue. Updating alone didn't help for some reason.

**Comment by tatsumoto-ren** [comment]
> If anybody else encounters this issue: On my machine I had to reinstall the plugin to fix this issue. Updating alone didn't help for some reason.

That's a well-known AnkiWeb bug. It checks for add-on updates, but reports that there's no new updates even when the author has already uploaded a new version. 

You don't have to remove the add-on though, just install it again (copy and paste the code), and you won't lose your settings.
